### ISSUE TITLE
Pressing esc crashes the game (Fabric 0.14.12, mc 1.19.3)

### ISSUE THREAD

**Issue by Kaizuto** [rikka0w0/LanServerProperties#24]
Pressing Esc/opening menu while ingame crashes game for some reason

Launcher: MultiMC (cracked version, UltimMC)
Other mods installed: Sodium

**Comment by polisGE** [comment]
same issue here (+ for 1.19.4), seems to work fine for 1.19.2 though. 

Launcher: Official
Extra mods: Sodium, Iridium, voice chat

**Comment by rikka0w0** [comment]
Due to internal changes in Minecraft, 1.19.3 and 1.19.4 are not compatible with 1.19.2 anymore. Please download the latest version of this mod:

For 1.19.3: https://github.com/rikka0w0/LanServerProperties/releases/tag/1.10_Forge_Fabric
For 1.19.4: https://github.com/rikka0w0/LanServerProperties/releases/tag/1.10.1_Forge_Fabric
